# Generated by Django 3.1.7 on 2021-03-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doc_id', models.IntegerField(db_column='doc_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=40)),
                ('speciality', models.CharField(db_column='speciality', max_length=40)),
                ('chamber_name', models.CharField(db_column='chamber_name', max_length=50)),
                ('consultation_hour', models.CharField(db_column='consultation_hour', max_length=20)),
                ('consultation_fee', models.IntegerField(db_column='consultation_fee')),
                ('contact_no', models.CharField(db_column='contact_no', max_length=20)),
                ('subdistrict', models.CharField(db_column='subdistrict', max_length=30)),
                ('district', models.CharField(db_column='district', max_length=30)),
                ('division', models.CharField(db_column='division', max_length=15)),
            ],
        ),
    ]
