# Generated by Django 3.1.7 on 2021-04-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subdistrict_council', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subdistrict_council',
            new_name='Subdistrict_counil',
        ),
    ]
