# Generated by Django 3.2 on 2021-05-21 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subdistrict_council', '0002_auto_20210408_1343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subdistrict_counil',
            new_name='Subdistrict_council',
        ),
    ]
