# Generated by Django 3.1.7 on 2021-04-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subdistrict_council', '0002_auto_20210405_1404'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subdistrict_counil',
            new_name='Subdistrict_council',
        ),
    ]
