# Generated by Django 3.1.7 on 2021-03-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bazar',
            name='id',
        ),
        migrations.AlterField(
            model_name='bazar',
            name='bazar_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
