# Generated by Django 3.1.7 on 2021-03-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0003_auto_20210325_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bazar',
            name='union',
        ),
    ]
