# Generated by Django 3.1.7 on 2021-03-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_station', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firestation',
            name='address',
            field=models.CharField(db_column='Address', max_length=50),
        ),
        migrations.AlterField(
            model_name='firestation',
            name='contact_no',
            field=models.IntegerField(db_column='Contact No'),
        ),
        migrations.AlterField(
            model_name='firestation',
            name='district',
            field=models.CharField(db_column='District', max_length=50),
        ),
        migrations.AlterField(
            model_name='firestation',
            name='division',
            field=models.CharField(db_column='Division', max_length=50),
        ),
        migrations.AlterField(
            model_name='firestation',
            name='firestation_id',
            field=models.IntegerField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firestation',
            name='firestation_name',
            field=models.CharField(db_column='Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='firestation',
            name='subdistrict',
            field=models.CharField(db_column='Subdistrict', max_length=50),
        ),
    ]
