# Generated by Django 3.1.7 on 2021-04-08 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_station', '0002_auto_20210325_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firestation',
            old_name='firestation_name',
            new_name='name',
        ),
    ]
